sonar.projectKey=hr-management-platform
sonar.projectName=HR Management Platform
sonar.sources=hr-platform-backend/src,hr-platform-frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.js
sonar.host.url=http://sonarqube:9000
